### PR TITLE
Fix text diff for 1st commit and deleted files

### PR DESCRIPTION
**Pull request by fcollonval**
This fixes the display of text diff in history for two cases:
- First commit (no previous commit)
- Commit at which the file is deleted

### CODE REVIEW

**Comment by ianhi** [comment]
Nice!

One note: I think this is still missing one case with deleted files. It works as I'd expected from the history panel, but if you try to get the diff of the file from the commit panel you will get an error
diff-of-deleted

**Comment by fcollonval** [comment]
Good catch @ianhi. I will extend this PR to cover that case.

Thank for reviewing

**Comment by fcollonval** [comment]
I added the versioned file being deleted case

**Review by ianhi — APPROVED** [review]
This is great thanks!

**Comment by fcollonval** [comment]
@meeseeksdev backport to 0.11.x

**Pull request merged**
