### PR TITLE
Bump TypeScript version

### PR DESCRIPTION
**Pull request by ian-r-rose**
Fix for #181

### CODE REVIEW

**Comment by LucasRoesler** [comment]
After trying this locally I also got these errors from `tsc`

```
src/components/components.tsx(177,11): error TS6133: '_manager' is declared but its value is never read.
src/components/components.tsx(179,11): error TS6133: '_runningSessions' is declared but its value is never read.
src/components/components.tsx(180,11): error TS6133: '_runningTerminals' is declared but its value is never read.
src/components/components.tsx(310,11): error TS6133: 'SF' is declared but its value is never read.
src/components/components.tsx(310,19): error TS6133: 'USF' is declared but its value is never read.
src/components/components.tsx(310,28): error TS6133: 'UTF' is declared but its value is never read.
```

Have you seen these too?

I am not super familiar with phosphorjs, so it isn't clear to me if the first 3 values are required but only used somewhere else in JupyterLab.  The last 3 values do actually seem like unused values, they are just ints that are declared in the `GitSessionNode.refresh` function, but they are not read from or returned anywhere.

**Comment by ian-r-rose** [comment]
Those are all unused variables in `@jupyterlab/git`. I think Typescript changed it's defaults for whether to complain about unused variables in the newer version. I'll add a commit removing them.

**Comment by LucasRoesler** [comment]
Have you tried installing it yet? I did the same changes locally and while it builds with npm/yarn. I haven't been able to install it in a docker image after deleting the extra variables.

My install command is just 
```
RUN cd /tmp/jupyterlab-git \
    && npm cache clean \
    && jupyter labextension link --debug .
```

Without the variables I got this error output

```
> node /opt/conda/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.3.2
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@jupyterlab/json-extension > react-highlighter@0.4.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react-dom@^15.0.0".
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has unmet peer dependency "react@^15.6.1".
warning "jupyterlab-git > @angular/core@4.4.6" has unmet peer dependency "rxjs@^5.0.1".
warning "jupyterlab-git > @angular/core@4.4.6" has unmet peer dependency "zone.js@^0.8.4".
[4/4] Building fresh packages...
warning Error running install script for optional dependency: "/opt/conda/share/jupyter/lab/staging/node_modules/canvas: Command failed.\nExit code: 1\nCommand: node-gyp rebuild\nArguments: \nDirectory: /opt/conda/share/jupyter/lab/staging/node_modules/canvas\nOutput:\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.4.0\ngyp info using node@6.12.2 | linux | x64\ngyp http GET https://nodejs.org/download/release/v6.12.2/node-v6.12.2-headers.tar.gz\ngyp http 200 https://nodejs.org/download/release/v6.12.2/node-v6.12.2-headers.tar.gz\ngyp http GET https://nodejs.org/download/release/v6.12.2/SHASUMS256.txt\ngyp http 200 https://nodejs.org/download/release/v6.12.2/SHASUMS256.txt\ngyp info spawn /usr/bin/python2\ngyp info spawn args [ '/opt/conda/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',\ngyp info spawn args   'binding.gyp',\ngyp info spawn args   '-f',\ngyp info spawn args   'make',\ngyp info spawn args   '-I',\ngyp info spawn args   '/opt/conda/share/jupyter/lab/staging/node_modules/canvas/build/config.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/opt/conda/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/home/jovyan/.node-gyp/6.12.2/include/node/common.gypi',\ngyp info spawn args   '-Dlibrary=shared_library',\ngyp info spawn args   '-Dvisibility=default',\ngyp info spawn args   '-Dnode_root_dir=/home/jovyan/.node-gyp/6.12.2',\ngyp info spawn args   '-Dnode_gyp_dir=/opt/conda/lib/node_modules/npm/node_modules/node-gyp',\ngyp info spawn args   '-Dnode_lib_file=node.lib',\ngyp info spawn args   '-Dmodule_root_dir=/opt/conda/share/jupyter/lab/staging/node_modules/canvas',\ngyp info spawn args   '--depth=.',\ngyp info spawn args   '--no-parallel',\ngyp info spawn args   '--generator-output',\ngyp info spawn args   'build',\ngyp info spawn args   '-Goutput_dir=.' ]\n./util/has_lib.sh: 31: ./util/has_lib.sh: pkg-config: not found\ngyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp\ngyp ERR! configure error \ngyp ERR! stack Error: `gyp` failed with exit code: 1\ngyp ERR! stack     at ChildProcess.onCpExit (/opt/conda/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)\ngyp ERR! stack     at emitTwo (events.js:106:13)\ngyp ERR! stack     at ChildProcess.emit (events.js:191:7)\ngyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)\ngyp ERR! System Linux 4.9.75-linuxkit-aufs\ngyp ERR! command \"/opt/conda/bin/node\" \"/opt/conda/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"\ngyp ERR! cwd /opt/conda/share/jupyter/lab/staging/node_modules/canvas\ngyp ERR! node -v v6.12.2\ngyp ERR! node-gyp -v v3.4.0\ngyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
success Saved lockfile.
```

But when I leave the variables but turn `unUsedVariables` off, it installs just fine

**Comment by ian-r-rose** [comment]
Yes, I installed it, and it worked just fine. The `node-gyp` error is unrelated, and can safely be ignored.

**Comment by dhirschfeld** [comment]
Does this need to be bumped to 3.1 now that JupyterLab is on that?

**Comment by blink1073** [comment]
This is superseded by #239

**Pull request closed without merging**
