### PR TITLE
Push/Pull frontend

### PR DESCRIPTION
**Pull request by jaipreet-s**
* Adds to buttons for Push and Pull in the PathHeader component
* All errors (for e.g. merge conflicts) are relayed back to the user via the error dialog box.
* Added unit tests for the PathHeader component.

### Testing

* Unit Tests added
* Local Testing
push_3
push_2
push_1

### CODE REVIEW

**Comment by jaipreet-s** [comment]
@saulshanabrook Are you available to review this today?

**Comment by jaipreet-s** [comment]
@chriszheng10

**Comment by saulshanabrook** [comment]
@jaipreet-s Yep, I will try this out.

**Comment by jaipreet-s** [comment]
@saulshanabrook 
`origin` (and `master`) have been removed as a required key in the input after PR #273. The upstream remote and branch to push **to**  is the currently set one. In case there is no upstream branch, an error is thrown like the one below. You will have to build the Python source locally to get the latest backend API since it's not in PyPI yet.

push_1

**Pull request merged**
