### PR TITLE
Format code using black

### PR DESCRIPTION
**Pull request by ianhi**
closes: https://github.com/jupyterlab/jupyterlab-git/issues/728

1. Formatted existing code `black .`
2. added `black . --check` to github actions
3. Saved formatting commit SHA in a file following https://github.com/psf/black/tree/20.8b1#migrating-your-code-style-without-ruining-git-blame
4. added pre-commit to setup.py and updated install instructions (https://github.com/psf/black/tree/20.8b1#version-control-integration)

@mlucool @fcollonval

### CODE REVIEW

**Comment by ianhi** [comment]
Tests fail because black is not available on python 3.5. This can be worked around with some if statements but it seems to get a little bit ugly as github actions don't support line level if statements. Given that python 3.5 is at the end of life in 9 days (september 13) I propose dropping it from the tests. Thoughts?

**Review by fcollonval — APPROVED** [review]
Thanks @ianhi 

I agree with you. We can drop testing against 3.5 and I went ahead by adding 3.9rc.

I reorganize a bit the CI script so only jupyterlab needs to be explicitly installed before the test step (to get `jlpm`).

**Comment by mlucool** [comment]
This is great! Does this commit add in a way to verify that future commits use black? i.e. have `black --check` as a test or similar?

**Comment by fcollonval** [comment]
@meeseeksdev backport to 0.11.x

**Pull request merged**
