### PR TITLE
Improve commit amend selection

### LINKED ISSUE #981: Improve UX for commit amend
UI-wise,what do you think about making it like the "Merge" button on GitHub (rather than a checkbox)? Here is a quick adoption of the GitHub's button:

| collapsed | expanded |
|--------|-------|
| Screenshot from 2021-07-17 14-30-06  | Screenshot from 2021-07-17 14-31-59 |

_Originally posted by @krassowski in https://github.com/jupyterlab/jupyterlab-git/issues/973#issuecomment-881899889_

### PR DESCRIPTION
**Pull request by fcollonval**
Fixes #981

image

### CODE REVIEW

**Comment by fcollonval** [comment]
cc @krassowski @SinaKhalili what do you think?

**Comment by krassowski** [comment]
I would use non-thin version of the caret. Should it be the down caret up up caret? Or maybe ⋮?

**Comment by fcollonval** [comment]
> I would consider using non-thin version of the caret. Should it be the down caret up up caret? Or maybe ⋮?

Indeed a ⋮icon will be more appropriate as the pop up will never be displayed below.

**Comment by fcollonval** [comment]
The icon has been updated to ⋮

**Pull request merged**
