### PR TITLE
Bug Fix: Replace lstrip with replace function

### PR DESCRIPTION
**Pull request by rrao24**
Fix for issue https://github.com/jupyterlab/jupyterlab-git/issues/848

### CODE REVIEW

**Comment by fcollonval** [comment]
Thanks @rrao24 for the contribution and for tracking it done.

Could you please add a problematic name in the unit test to keep track of this improvement?

The relevant test is there https://github.com/jupyterlab/jupyterlab-git/blob/e3cae9efcdeb3e14e1b994832b9118ee2f00af59/jupyterlab_git/tests/test_branch.py#L413

If you are not familiar with pytest let me know, I'll provide help.

**Review by fcollonval — CHANGES_REQUESTED** [review]
Please add a relevant unit test

**Comment by rrao24** [comment]
@fcollonval Done, ready for another review.

**Review by fcollonval — APPROVED** [review]
@rrao24 Thanks a lot for the quick addition.

**Comment by rrao24** [comment]
@fcollonval Do you know when you might be planning to cut a new release including this bug fix?

**Comment by fcollonval** [comment]
@rrao24 The release is in progress. v0.23.3 should be available shortly on pypi and npm and a bit later on conda-forge.

**Pull request merged**
