### PR TITLE
Setup puppeteer and add basic browser test

### PR DESCRIPTION
**Pull request by neelamgehlot**
```
→ python -m tests.test-browser.run_browser_test
[C 19:46:29.223 BrowserApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://127.0.0.1:8888/lab/?token=a3c8f1b5d588c1c352a670f458ce63a15d2636f1717e2809
Starting Chrome Headless
Navigating to page: http://127.0.0.1:8888/lab/?token=a3c8f1b5d588c1c352a670f458ce63a15d2636f1717e2809
[I 19:46:29.668 BrowserApp] 302 GET /lab/?token=a3c8f1b5d588c1c352a670f458ce63a15d2636f1717e2809 (127.0.0.1) 1.23ms
Waiting for page to load...
Waiting for application to start...
Chrome test complete
[I 19:46:31.913 BrowserApp] Shutting down 0 kernels
```

### CODE REVIEW

**Comment by dleen** [comment]
I'm running into the same error as Saul.

**Comment by neelamgehlot** [comment]
> Code looks fine but hitting the same error as Saul.

Hmmm, it runs fine for me
```
± |headless-browser-testing → origin/master ↑3 {19} U:1 ✗| → python -m tests.test-browser.run_browser_test
\[W 13:26:26.752 BrowserApp] Error loading server extension jupyter_nbextensions_configurator
    Traceback (most recent call last):
      File "/Users/neelamg/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1546, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/neelamg/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'
[I 13:26:26.771 BrowserApp] JupyterLab extension loaded from /Users/neelamg/anaconda3/lib/python3.6/site-packages/jupyterlab
[I 13:26:26.771 BrowserApp] JupyterLab application directory is /Users/neelamg/anaconda3/share/jupyter/lab
[W 13:26:26.899 BrowserApp] JupyterLab server extension not enabled, manually loading...
[I 13:26:26.919 BrowserApp] JupyterLab extension loaded from /Users/neelamg/anaconda3/lib/python3.6/site-packages/jupyterlab
[I 13:26:26.919 BrowserApp] JupyterLab application directory is /Users/neelamg/anaconda3/share/jupyter/lab
[I 13:26:26.920 BrowserApp] Serving notebooks from local directory: /Users/neelamg/github-workspace/jupyterlab-git
[I 13:26:26.920 BrowserApp] The Jupyter Notebook is running at:
[I 13:26:26.920 BrowserApp] http://127.0.0.1:8888/lab/?token=07f8330a1614e723cabc1a9733cc5b6923b7fe2c65d699c2
[I 13:26:26.920 BrowserApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 13:26:26.921 BrowserApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://127.0.0.1:8888/lab/?token=07f8330a1614e723cabc1a9733cc5b6923b7fe2c65d699c2
Starting Chrome Headless
Navigating to page: http://127.0.0.1:8888/lab/?token=07f8330a1614e723cabc1a9733cc5b6923b7fe2c65d699c2
[I 13:26:28.503 BrowserApp] 302 GET /lab/?token=07f8330a1614e723cabc1a9733cc5b6923b7fe2c65d699c2 (127.0.0.1) 2.59ms
Waiting for page to load...
Waiting for application to start...
Chrome test complete
[I 13:26:31.630 BrowserApp] Shutting down 0 kernels
```

**Comment by dleen** [comment]
> > Code looks fine but hitting the same error as Saul.
> 
> Hmmm, it runs fine for me
> 

Did you use the same `node_modules` from before or start from a clean `npm install`?

**Comment by neelamgehlot** [comment]
Accidently deleted the branch, new PR https://github.com/jupyterlab/jupyterlab-git/pull/354

**Pull request closed without merging**
