### PR TITLE
Test on multiple python 3.x

### PR DESCRIPTION
**Pull request by fcollonval**

### CODE REVIEW

**Comment by fcollonval** [comment]
Thanks for the approval @jaipreet-s 
I'll fix the conflicts. Do we still want to test on Python 3.5 as it reached end of life and conda package are no more built for it?

**Comment by jaipreet-s** [comment]
> I'll fix the conflicts. Do we still want to test on Python 3.5 as it reached end of life and conda package are no more built for it?

Makes sense to drop 3.5. Thanks.

**Comment by fcollonval** [comment]
@meeseeksdev backport to 0.11.x

**Comment by fcollonval** [comment]
@meeseeksdev backport to 0.11.x

Try again

**Pull request merged**
