### PR TITLE
Add default revert commit message and resizable commit message box

### PR DESCRIPTION
**Pull request by mlucool**
This PR

-   replaces the reset/revert dialog with a Material UI dialog to ensure similar UX to dialog for creating branches.
-   provides a default commit message when reverting changes introduced by a commit.
-   replaces a single line input element with a separate input element for a commit message summary and a resizable `textarea` for a commit description, in order to ensure a similar UX as the normal commit box.
-   adds up and down caret icons (similar to branch menu button in side panel) to provide visual indication that commit info can be expanded and collapsed.
-   updates messages to use more consistent and informative language.
-   adds source code documentation.
-   cleans-up component methods.
-   adjusts UI element styles (e.g., cursors and disabling upon clicking the cancel/submit button).
-   ensures that a `headChanged` event is emitted upon committing (without this change, reverting a commit does not cause the history panel to refresh).
-   renames the component for reseting and reverting commits to be more in line with Git terminology.
-   simplifies component methods.
-   adjusts icon alignment.
-   aligns commit header info to ensure consistent vertical alignment.
-   updates component tests.

## Screenshots

-   Updates to history sidebar (note the aligned commit header info, carets, and updated expanded information presentation):

Screen Shot 2020-03-21 at 3 47 35 PM

-   Dialog in light theme (note the default commit message placeholders when reverting changes):

Screen Shot 2020-03-21 at 3 58 05 PM

-   Dialog in dark theme:

Screen Shot 2020-03-21 at 3 58 24 PM

### CODE REVIEW

**Comment by fcollonval** [comment]
Thanks for your contribution @mlucool

**Comment by kgryte** [comment]
@telamonian @fcollonval Updated this PR. This should be ready for review!

**Comment by kgryte** [comment]
@telamonian I will pull down the latest `master` and see what needs to change.

**Comment by kgryte** [comment]
@telamonian This PR should be ready to go! Updated the OP to reflect the changes. Let me know if anything else needs to be done!

**Comment by kgryte** [comment]
@telamonian Thanks for reviewing!

**Pull request merged**
