### PR TITLE
Visual diff for plain text files

### PR DESCRIPTION
**Pull request by timnlupo**
This change introduces the feature to be able to view plain text diffs. It uses Monaco to render the diffs for supported files and ties into the existing <Diff /> component from visual diffs for Notebooks.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
Does this resolve #252?

**Comment by fcollonval** [comment]
Thanks @timnlupo for this great work.

Your current PR highlights one point I was fearing when using Monaco: the bundle size. From the travis build, it looks we may load more than 10MiB to show some diffs (see below). Would it be possible to include only the `editor` and not the language workers? It seems it is the default according to https://github.com/jupyterlab/jupyterlab-git/pull/388/files#diff-b7a2b01fa406ddc8bfdcf38ea0eaf567R32.


```bash
                                                            Asset      Size         Chunks             Chunk Names
       JUPYTERLAB_FILE_LOADER_jupyterlab-git-css.worker.bundle.js  1.57 MiB     css.worker  [emitted]  css.worker
   JUPYTERLAB_FILE_LOADER_jupyterlab-git-css.worker.bundle.js.map  1.68 MiB     css.worker  [emitted]  css.worker
    JUPYTERLAB_FILE_LOADER_jupyterlab-git-editor.worker.bundle.js   372 KiB  editor.worker  [emitted]  editor.worker
JUPYTERLAB_FILE_LOADER_jupyterlab-git-editor.worker.bundle.js.map   379 KiB  editor.worker  [emitted]  editor.worker
      JUPYTERLAB_FILE_LOADER_jupyterlab-git-html.worker.bundle.js  1.02 MiB    html.worker  [emitted]  html.worker
  JUPYTERLAB_FILE_LOADER_jupyterlab-git-html.worker.bundle.js.map  1.09 MiB    html.worker  [emitted]  html.worker
      JUPYTERLAB_FILE_LOADER_jupyterlab-git-json.worker.bundle.js   745 KiB    json.worker  [emitted]  json.worker
  JUPYTERLAB_FILE_LOADER_jupyterlab-git-json.worker.bundle.js.map   753 KiB    json.worker  [emitted]  json.worker
        JUPYTERLAB_FILE_LOADER_jupyterlab-git-ts.worker.bundle.js  8.27 MiB      ts.worker  [emitted]  ts.worker
    JUPYTERLAB_FILE_LOADER_jupyterlab-git-ts.worker.bundle.js.map  9.22 MiB      ts.worker  [emitted]  ts.worker
```

**Comment by jaipreet-s** [comment]
Hi @fcollonval , @timnlupo was doing this work as part of his internship w/ my team. His internship is over so this work is stalled now. 

Would you like to take over this work and drive it forward? If so, it would be fine to take Tim's code as a baseline and then build on top of it.

**Comment by fcollonval** [comment]
@jaipreet-s, I gladly push this forward.

**Comment by timnlupo** [comment]
Hi @fcollonval , thanks for taking this over. I do believe you can only include the `editor` worker. From [this issue](https://github.com/microsoft/monaco-editor/issues/793):

> "The webworkers are responsible for enhanced suggestions and syntax errors etcs. With setting the editor language to JSON everything is going to be loaded, not only the colors."

Since the diff viewer is read only, I don't believe those features are necessary. Let me know if you have any other questions.

**Comment by fcollonval** [comment]
Superseeded by #406

**Pull request closed without merging**
