### PR TITLE
Refactor user feedbacks

### LINKED ISSUE #725: Cancelling a push by clicking away from the dialog incorrectly asks for git credentials
## Description
In the below gif I interact with the push dialog in three different ways
1. Let it finish
    - Works - no issues with credentials
2. Dismiss using the dismiss button
   - Works as expected
3. Cancel the full screen modal by clicking somewhere other than the push dialog
    - This incorrectly brings up the credentials dialog

pushing

## Reproduce

With setting ` "blockWhileCommandExecutes": true`:

1. Enter a repo you have approriate credentials for
2. click push button 
3. click somewhere on the screen
4. Git credentials box pops up

## Expected behavior

Credentials box does not pop up

## Context

- Python package version: 0.21.0a0

- Extension version: 0.21.0a0

- Git version: 2.25.1

- Operating System and its version: PopOs 20.04

No interesting output in either console

### PR DESCRIPTION
**Pull request by fcollonval**
This PR:
- Extract the task manager functions from the model to be handled by a specific object.
- Introduce a logger to pass log message to a unique alert component from anywhere in the extension
  - The error object can be passed along side the log message. So the user can click a button on the alert component to display error details; this avoid opening two visual feedback: a dialog and the error alert.

Consequences:
- Fixes #725 
- More homogeneous user experience for push, pull and clone:
  - they use the same notification system (no more ugly dialog with spinner)
  - they use the same logic to handle git command execution with the need to request authentication
- Easy to add the new logger on feature; the delay and visibility logic is encapsulated in the notification system
- Code refactoring: -400 lines of duplicated code.

### CODE REVIEW

**Comment by ianhi** [comment]
> they use the same notification system (no more ugly dialog with spinner)

:tada: :tada: :tada: This is fantastic!

Poking around with using it and found one issue so far. I can have a push fail but the UI appears as though the push succeeded.
1. change remote to a nonexistent repo: `git@github.com:fcollonval/git-expt.git`
2. Push
In this GIF the left is jlab, top right is a terminal with `jupyter lab --watch`, bottom right is another terminal for git commands:
push-broken

Error is this:
```
[E 16:32:13.896 LabApp] {
      "Host": "localhost:8889",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
      "Accept": "*/*",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://localhost:8889/lab",
      "Content-Type": "application/json",
      "Authorization": "token 275157f056cf16d00bc0e36d0e7975c4117186bcfaa1bc04",
      "X-Xsrftoken": "2|5810ace8|0518e62ea541d39ef684884b540b19d1|1600798127",
      "Origin": "http://localhost:8889",
      "Content-Length": "55",
      "Dnt": "1",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1600806729|23:username-localhost-8888|44:NGMwZWUxYjhlOWZlNGE1ZTgwNWY2OTQ0MTg1ZTQ0MDg=|c2c24050501725772cc41838772733e1364a9676ba756998112c631b5eefb7a7\"; username-localhost-8890=\"2|1:0|10:1600054697|23:username-localhost-8890|44:MGUxMTYyMmI5ZWZlNGFjOGI1MWVjYjg5OTVlMWIyOTg=|e2a8c35a006e2947cf8f7c8dc03d98cb106b25a812597280ee92e7ba0ae350e1\"; username-localhost-8891=\"2|1:0|10:1599785087|23:username-localhost-8891|44:NTczZDQ3ZjFjNjRlNGZjMjlhODU0YzEzNzA1YjUyNjQ=|723d574d7f87b419fb9f175ed05da61ad0bc40e0fd530323c8a2aa2b91feed01\"; username-localhost-8892=\"2|1:0|10:1599894500|23:username-localhost-8892|44:NTZjY2YwOTYyNDZkNGQ2OWJkZGI0ZGY0ODAwYzgxNjc=|453b47c4ed8f829ab5732e1fb61ea6277ce0919f9f8c0201e431fba580d8b57a\"; username-localhost-8889=\"2|1:0|10:1600806729|23:username-localhost-8889|44:NzFlMDVhNTlhOWJmNGI2ZGJkYzNlN2UwMmVjYmE4NDI=|8e745328e8e5a75c4efd71ee3cf95e0609ea9e55f2083a8edaa1ea84d61fc85f\"; username-localhost-8872=\"2|1:0|10:1598366798|23:username-localhost-8872|44:N2NjYzZhNjczNmM4NDgyN2JmMGExYTkwYzg2NGRhMmI=|0fb7b44e6e7733c7644b010705095e7e9cee55db3e29ec3d5f370e21f3ff091a\"; _xsrf=2|5810ace8|0518e62ea541d39ef684884b540b19d1|1600798127",
      "Pragma": "no-cache",
      "Cache-Control": "no-cache"
    }
[E 16:32:13.896 LabApp] 500 POST /git/push?1600806729468 (::1) 4417.98ms referer=http://localhost:8889/lab
[E 16:32:54.955 LabApp] {
      "Host": "localhost:8889",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
      "Accept": "*/*",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://localhost:8889/lab",
      "Content-Type": "application/json",
      "Authorization": "token 275157f056cf16d00bc0e36d0e7975c4117186bcfaa1bc04",
      "X-Xsrftoken": "2|5810ace8|0518e62ea541d39ef684884b540b19d1|1600798127",
      "Origin": "http://localhost:8889",
      "Content-Length": "55",
      "Dnt": "1",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1600806769|23:username-localhost-8888|44:OTQ0MjY3MTQwMDkwNDY0OWI2YzNiN2QwZWZjN2FiNTc=|0ee31427816b722be00864e65e14e8e398cdcfade3c19a8e1b8eae72237e3720\"; username-localhost-8890=\"2|1:0|10:1600054697|23:username-localhost-8890|44:MGUxMTYyMmI5ZWZlNGFjOGI1MWVjYjg5OTVlMWIyOTg=|e2a8c35a006e2947cf8f7c8dc03d98cb106b25a812597280ee92e7ba0ae350e1\"; username-localhost-8891=\"2|1:0|10:1599785087|23:username-localhost-8891|44:NTczZDQ3ZjFjNjRlNGZjMjlhODU0YzEzNzA1YjUyNjQ=|723d574d7f87b419fb9f175ed05da61ad0bc40e0fd530323c8a2aa2b91feed01\"; username-localhost-8892=\"2|1:0|10:1599894500|23:username-localhost-8892|44:NTZjY2YwOTYyNDZkNGQ2OWJkZGI0ZGY0ODAwYzgxNjc=|453b47c4ed8f829ab5732e1fb61ea6277ce0919f9f8c0201e431fba580d8b57a\"; username-localhost-8889=\"2|1:0|10:1600806773|23:username-localhost-8889|44:ZDRiZTEzNjhlYzZmNDI1YmIyZjMyMTlhYWQzNTc0NGY=|1bc3888f29846204cfb8932704b349e5af61a49fdad769423651e6d4085c6de8\"; username-localhost-8872=\"2|1:0|10:1598366798|23:username-localhost-8872|44:N2NjYzZhNjczNmM4NDgyN2JmMGExYTkwYzg2NGRhMmI=|0fb7b44e6e7733c7644b010705095e7e9cee55db3e29ec3d5f370e21f3ff091a\"; _xsrf=2|5810ace8|0518e62ea541d39ef684884b540b19d1|1600798127",
      "Pragma": "no-cache",
      "Cache-Control": "no-cache"
    }
[E 16:32:54.955 LabApp] 500 POST /git/push?1600806774569 (::1) 376.61ms referer=http://localhost:8889/lab

```

**Comment by ianhi** [comment]
With an https remote there are lots of console errors:
recursion
```
Uncaught InternalError: too much recursion
    handleEvent index.es6.js:10600
    _evtFocus dialog.js:285
    handleEvent dialog.js:174
    contain Unstable_TrapFocus.js:77
    _evtFocus dialog.js:285
    handleEvent dialog.js:174
    contain Unstable_TrapFocus.js:77
    _evtFocus dialog.js:285
    handleEvent dialog.js:174
    contain Unstable_TrapFocus.js:77

```

**Comment by fcollonval** [comment]
Thanks for testing this one @ianhi And good catch for the credentials - although this looks tricky to solve :cry:

**Comment by fcollonval** [comment]
@ianhi Thanks again for testing. I corrected the bug you discovered. Could you have a second look at this PR?

**Comment by ianhi** [comment]
> Could you have a second look at this PR?

Will do this afternoon after soccer with the housemates.

**Review by ianhi — DISMISSED** [review]
I tried my hardest to be a pathological user and break this, but couldn't find any bugs :no_entry_sign: :bug:.

 This is a really nice improvement both for the user and for unifying the logic of git actions. Unless you want to add anything more then I think all that remains is a rebase and merge.

**Comment by ianhi** [comment]
I actually did find one weird edge case. But it's so niche that I don't think it really matters. If you:
1. Have an `https` remote
2. Run jupyterlab from the vscode terminal
3. push from jlab-git

then vscode will eat the authorization
wot

but I don't think that should block merging this. I don't even think that's something that's in our control

**Comment by fcollonval** [comment]
Thanks for testing it @ianhi 

I don't think it is related to JupyterLab but more about the authorization mechanism of VSCode. So I'll correct the conflict and merge.

**Comment by ianhi** [comment]
nice. With this and https://github.com/jupyterlab/jupyterlab-git/pull/767 new release? Or do you want to finish the SVG work (https://github.com/jupyterlab/jupyterlab-git/pull/783) first?

**Pull request merged**
