### PR TITLE
Rework frontend

### LINKED ISSUE #346: Open Terminal option in Git menu doesn't resolve Jupyter home dir
The Open Terminal option does a "cd $REPONAME" which opens the terminal on the `home_dir`/$REPONAME

This doesn't factor in the base directory of the Jupyter server.

### LINKED ISSUE #408: Separate model and vue in frontend
## Description

The frontend architecture could be improved greatly by introducing a model object separated from the UI elements.

That object should be the owner of the selected path, the bridge to the back end and the exported token.

This will help maintenance, reduce the objects to pass down the react tree and be of higher value for other extensions interested in reusing git functions.

### LINKED ISSUE #434: clicking on git icon produces JS errors ("props.onClick is not a function")
FYI Clicking on the git icon on the top-right of the image below is what generate the props.onClick is not a function error. 

image

<pre>
jovyan@mini ~ jupyter labextension list
JupyterLab v1.1.4
Known labextensions:
   app dir: /usr/local/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.0.3  enabled  OK
        @jupyterlab/git v0.8.2  enabled  OK
        @ryantam626/jupyterlab_code_formatter v0.6.0  enabled  OK
        jupyterlab-jupytext v1.0.2  enabled  OK
        jupyterlab-server-proxy v2.0.0  enabled  OK*
        nbdime-jupyterlab v1.0.0  enabled  OK

   local extensions:
        jupyterlab-server-proxy: /tmp/jupyter-server-proxy/jupyterlab-server-proxy
</pre>

### LINKED ISSUE #436: The sidepanel widget does not restore correctly
Currently, even if a user is within a repository, for whatever reason on startup of jlab (and also on page refresh) the user has to first manually click the refresh button at the top of the `jupyterlab-git` sidepanel UI in order to load their repo into the sidepanel. This should happen automatically.

### PR DESCRIPTION
**Pull request by fcollonval**
The main purpose of this is to close #408; i.e. creating a model for the git repository that can be obtained through a token to third-party extensions and that centralizes the state for the components (although I'm unsure I will succeed on that).

But diving into the code and in light with additional feature now available in JupyterLab, this brings also simplification to the code and try to improve the overall code structure. 

This will:
- fix #436, 
- fix #346 (superseeding #347) 
- and fix #434.

TODO
- [x] Context menu is broken, need to be fixed
- [x] Correct unit tests
- [x] Move `CommitBox` as `FileList` child
- [x] ~~Move the refresh function part related to current folder status at `FileList` level.~~
- [x] Split the refresh function
- [x] Add test for model
- [x] Add doc for the model API

## User facing changes

- The second help link is now: https://git-scm.com/doc - what seems much more interesting than a generic web search engine.

### CODE REVIEW

**Comment by fcollonval** [comment]
@telamonian @jaipreet-s 
Having user interaction with hidden components like for switching branches or creating a new branch, makes the react stack complicated. It would be easier to switch to user dialog boxes. What do you think?

**Comment by fcollonval** [comment]
@telamonian could you review this PR please? From the code modifications, I did all the actions I had in mind. I still have to write unit tests for the model and improve the interfaces documentation.

**Comment by telamonian** [comment]
@fcollonval That was actually already on my TODO list for today. I'll let you know how it goes

**Comment by telamonian** [comment]
I'm still working through the review of this (there's a lot). I did find a couple of bugs. For example, when you click on the history tab, the tabbar with the history/current branch tabs disappears.

Caveat: I haven't looked at the changes you just force pushed yet. I'll do that this afternoon, and also try to get the review done then.

**Comment by telamonian** [comment]
Okay, it looks like the latest changes have in fact fixed the disappearing tabbar bug that I was seeing.

**Comment by fcollonval** [comment]
> I'm still working through the review of this (there's a lot)

Thanks, and I try to keep things more atomic in the future ;-)

**Pull request merged**
