### PR TITLE
UI Design 

### PR DESCRIPTION
**Pull request by hzarea**
Here are some initial changes for the UI of the plugin... more to come!

### CODE REVIEW

**Comment by ellisonbg** [comment]
@hzarea great! Can you post screen shots of the design here. We try to do that with any design related PR so folks can see the changes visually. Thanks!

**Comment by hzarea** [comment]
@ellisonbg oops I forgot to include them! I've made a bunch of changes since yesterday, but here is what this older pull request looks like:

screen shot 2017-08-15 at 5 38 47 pm

**Comment by hzarea** [comment]
Here is a more updated version: 
screen shot 2017-08-15 at 5 58 10 pm
screen shot 2017-08-15 at 5 58 58 pm

**Comment by ellisonbg** [comment]
Thanks for posting the screenshots. Can you also open some new issues on this repo describing the different UI/UX design things you are planning on doing? That helps others to understand where we are at and going.

**Pull request closed without merging**
