### PR TITLE
Update git clone placeholder text

### PR DESCRIPTION
**Pull request by danielgruesso**
Update git clone placeholder text to illustrate integration works with any git host

### CODE REVIEW

**Comment by danielgruesso** [comment]
@saulshanabrook would you be able to kindly assist with this small change?

**Comment by danielgruesso** [comment]
Thank you @saulshanabrook ! Anything else required prior to merge?

**Comment by jaipreet-s** [comment]
LGTM. Thanks for the contribution.

**Comment by danielgruesso** [comment]
Thank you @jaipreet-s

**Pull request merged**
