### PR TITLE
Upgrade to jupyterlab 4

### PR DESCRIPTION
**Pull request by HaudinFlorence**
Update jupyterlab-git for jupyterlab 4

Fixes https://github.com/jupyterlab/jupyterlab-git/issues/1245

### CODE REVIEW

**Comment by mahendrapaipuri** [comment]
What is the status of this PR? Is there any timeline when it will be finished?

**Comment by HaudinFlorence** [comment]
> What is the status of this PR? Is there any timeline when it will be finished?

Thanks @mahendrapaipuri for your interest. It is still a work in progress.

**Comment by krassowski** [comment]
@HaudinFlorence it looks like this one accumulated a number of merge conflicts. I or one of my colleagues would be happy to push this forward by resolving the conflicts and fixing up any outstanding issues. Did you plan to work on this PR anytime soon, or should we go ahead and open a new PR (or a PR against your branch - whichever preferred)?

**Comment by HaudinFlorence** [comment]
> @HaudinFlorence it looks like this one accumulated a number of merge conflicts. I or one of my colleagues would be happy to push this forward by resolving the conflicts and fixing up any outstanding issues. Did you plan to work on this PR anytime soon, or should we go ahead and open a new PR (or a PR against your branch - whichever preferred)?

@krassowski Thanks for proposing some help. We are planning to rework on this PR. The update of jupyterlab-git to jupyterlab4 requires the migration of nbdime to codemirror6. So we are currently working on it since the past few weeks. We will then go back to this PR. In the meantime, if you want to rebase it, please feel free to do it. Thanks. cc @fcollonval @JohanMabille

**Comment by krassowski** [comment]
Sounds like a plan! If you get stuck with some issue on CodeMirror6 transition feel welcome to ping me, I am now working on LSP which has a large surface of contact with CodeMirror6.

**Comment by dlqqq** [comment]
@HaudinFlorence Hello Florence! I recently upgraded both [Jupyter Scheduler](https://github.com/jupyter-server/jupyter-scheduler/pull/402) and [Jupyter AI](https://github.com/jupyterlab/jupyter-ai/pull/296) to JupyterLab 4, and I'd be happy to help with this migration. Our team at AWS has a vested interest in getting `jupyterlab-git` JL4-compatible before the end of the year, ideally within the next month or two, so we are happy to be of assistance.

Would you be open to meeting virtually sometime to see how I can help? I also fully understand if you're already 99% finished and would like to complete it alone, just let me know. My email is on my GitHub profile.

**Comment by HaudinFlorence** [comment]
@dlqqq Thanks for your message and for proposing some help. We are still in the process of migrating nbdime to codemirror6 and are close to have a working version with most of the current features https://github.com/jupyter/nbdime/pull/664. Then we will go back to this PR.

**Comment by psychemedia** [comment]
just a comment on timelines; I'm in the edu sector and like many other educators we're on a sprint over summer updating things for September academic years starts; not having `jupyterlab-git` is a blocker for many educators who want to migrate to v4 and expect students to use git in support of coursework (things tend to get locked in for the forthcoming academic year over the summer).

**Comment by HaudinFlorence** [comment]
@psychemedia Thanks for pointing this timelines out. We are still on nbdime update and will then move back to finalizing the update of jupyterlab-git.

**Comment by JasonWeill** [comment]
@HaudinFlorence Thanks for your work on the related nbdime PR! Is there anything we can do to help that PR or this PR move forward? Do you have an estimate for when you would expect this PR to be ready for submission?

**Comment by HaudinFlorence** [comment]
> @HaudinFlorence Thanks for your work on the related nbdime PR! Is there anything we can do to help that PR or this PR move forward? Do you have an estimate for when you would expect this PR to be ready for submission?

@JasonWeill Thanks for your message and proposition for help. The PR on updating nbdime to jupyterlab4 and so to CM6 is almost ready for review (it will be tagged to request review today hopefully). Feel free to have a look at it: https://github.com/jupyter/nbdime/pull/664
Then it will depend on the time required for the review of nbdime PR and for having a new version to be used with `jupyterlab-git`. So it is a bit difficult to give a precise timeline. But things are progressing.

**Comment by HaudinFlorence** [comment]
The PR for updating nbdime to jupyterlab4 is ready for review here: https://github.com/jupyter/nbdime/pull/664.

**Comment by vkaidalov** [comment]
Hi @HaudinFlorence!
Given that https://github.com/jupyter/nbdime/pull/673 is almost finished, would you be so kind to tell how much time will be needed to finish this MR? At least a very rough estimation, e.g. somewhere in the end of this month? Thanks

**Comment by HaudinFlorence** [comment]
> Hi @HaudinFlorence! Given that [jupyter/nbdime#673](https://github.com/jupyter/nbdime/pull/673) is almost finished, would you be so kind to tell how much time will be needed to finish this MR? At least a very rough estimation, e.g. somewhere in the end of this month? Thanks

Hi @vkaidalov,
The estimated time to finish this PR is mid October but there are still blockers making any target date very provisional.
Thanks.

**Comment by JasonWeill** [comment]
@HaudinFlorence Thank you very much for your hard work on the nbdime PR! What other blockers affect this PR?

**Comment by HaudinFlorence** [comment]
> @HaudinFlorence Thank you very much for your hard work on the nbdime PR! What other blockers affect this PR?

Hi @JasonWeill,
Thanks for your message. The blocker that is the most difficult to evaluate is improving nbdime API for diff and merge views in such a way that it can be reused in jupyterlab-git for plain text files as CM6 does not have merge addon replacement.

**Comment by Khagesh16** [comment]
Please, provide jlab 4 support

**Comment by HaudinFlorence** [comment]
> Can you elaborate on what is missing in https://github.com/codemirror/merge? Maybe we could contribute to it to enable reuse in jupyterlb-git? Are there upstream issues open that we could help with? For the record there are different ways of contributing and the author was raising funds some time ago: https://discuss.codemirror.net/t/merge-view-implementation/5072

@krassowski I don't know how to answer these points and how much effort it would be to make a 3 way-merge view in CM6 if it is the point raised here. I guess that @fcollonval and @JohanMabille have answer on your questions.

**Comment by fcollonval** [comment]
For all people willing to push this forward, there are two meta issues on nbdime listing actions needed to help with this:
- [required actions] https://github.com/jupyter/nbdime/issues/680
- [other points] https://github.com/jupyter/nbdime/issues/659

Please assign yourself to an issue when you start working on it so that we can split efficiently the effort between those issues.

**Comment by RafaelClovr** [comment]
Hi, one question, if pyhton 3.7 is deprecated, should be removed from CI?

**Comment by benz0li** [comment]
This extension not yet supporting JupyterLab 4 currently blocks a smooth transition to Python 3.12.

The most essential[^1] extensions maintained by Jupyter team + jupyterlab-contrib are already supporting JupyterLab 4.  
ℹ️ See https://github.com/jupyterlab/jupyterlab/issues/14590 for more information.

[^1]: I consider this extension an essential extension.

Cross reference: https://github.com/b-data/jupyterlab-python-docker-stack/issues/5

**Comment by fcollonval** [comment]
I think @benz0li you are misinformed. Migrating to Python 3.12 does not require JupyterLab 4, what is blocking a Python upgrade above 3.10 is summarized in that issue: https://github.com/jupyterlab/jupyterlab-git/issues/1261

**Comment by benz0li** [comment]
> what is blocking a Python upgrade above 3.10 is summarized in that issue: #1261

If one uses basic [HTTP] authentication: Yes. No problems when connecting via SSH.

I have been using this extension with Python 3.11 for some time now.

**Comment by ptempier** [comment]
This issue is open since a really long time.
Could we get a degraded git plugin that works only in ssh then ?
So a few peoples can use this as a workaround, waiting for the http auth to work ?

**Comment by radicodes** [comment]
> Hi @vkaidalov, Thanks for your message. The estimated time to finish this PR is mid October but there are still blockers making any target date very provisional.

Is mid-october still the plan here?  My team is currently blocked by this, so just wanting to check in.  Thank you!

**Comment by benz0li** [comment]
@fcollonval Is there an approximate timeframe for the release that will support JupyterLab 4?

**Comment by krassowski** [comment]
@benz0li it will likely happen once final nbdime version is released. In the meantime you can help by testing the latest prerelease (currently [v0.50.0a0](https://github.com/jupyterlab/jupyterlab-git/releases/tag/v0.50.0a0)) and report any issues you see.

**Comment by benz0li** [comment]
> @benz0li it will likely happen once final nbdime version is released.

@krassowski Thanks for the info. This is perfectly fine.

> In the meantime you can help by testing the latest prerelease (currently [v0.50.0a0](https://github.com/jupyterlab/jupyterlab-git/releases/tag/v0.50.0a0)) and report any issues you see.

I did very basic *smoke testing* and it worked fine.

---

Unrelated to this issue but worth mentioning: There is also https://github.com/jupyterlab/jupyterlab_pygments/pull/31: Progress seems to have stalled.

**Pull request merged**
