### PR TITLE
Fix #551

### LINKED ISSUE #551: Problem with install in the build step
Having `jlpm install` in the [package.json's build](https://github.com/jupyterlab/jupyterlab-git/blob/master/package.json#L16) is somewhat problematic. I happened to have set `NODE_ENV=production yarn run build`, which yarn took to mean uninstall all my dev dependencies.

Not a high priority, but thought it was worth flagging.

### PR DESCRIPTION
**Pull request by fcollonval**
To have install + build, just execute `jlpm`.

As the clean command is not set in the _prepare_ stage, this avoid multiple compilation (the reason it was remove in 49e3261e9214b27441f0d0e1de7d1a0aa674a600).

### CODE REVIEW

**Comment by kgryte** [comment]
Why `prepare` and not `postinstall`?

**Comment by fcollonval** [comment]
> Why `prepare` and not `postinstall`?

I followed the practice for JLab extensions as established by the extension template.

**Comment by kgryte** [comment]
We should update the README, as well.

**Comment by fcollonval** [comment]
> We should update the README, as well.

Good catch, thanks

**Comment by fcollonval** [comment]
@meeseeksdev backport to 0.11.x

**Pull request merged**
