### PR TITLE
Virtualized files list

### LINKED ISSUE #667: a high number of untracked files make the extension and jupyter lab unresponsive
I have a repo with a lot (10 000+) untracked files (mostly intermediate figures and tables I do not need to track, not excluded through a .gitignore) which get listed in the corresponding section of the UI but make the extension and the whole jupyter lab unresponsive.

Is there any remedy?

### LINKED ISSUE #703: Git status API recursively lists all untracked files causing browsers to hang
## Description

The current implementation of git status uses the `-u` flag which recursively lists _all_ untracked files in _all_ sub-directories in a Git repository. Jupyter users often work with data sets that involve a large number of small files. When such datasets are untar'd into a working Git repository, this causes the `/git/status` API to return an unbounded response and freezes the entire JupyterLab front-end as well as the browser.

This operation is *not* paginated and the amount of files that are returned is unbounded.  For e.g., see the notebook [here](https://github.com/udacity/sagemaker-deployment/blob/master/Project/SageMaker%20Project.ipynb). This downloads the IMDb dataset. Downloading the data causes **the entire JupyterLab application to become unresponsive and the browser to hang**. I noticed my browser taking ~10GB of RAM and causing general machine slowness. 

## Reproduce

(Warning: This will hang your browser) 

Download and untar the [IMDB Dataset](http://ai.stanford.edu/~amaas/data/sentiment/) in your working directory.

Alternatively, 
1. `git clone https://github.com/udacity/sagemaker-deployment`
2. Run the `SageMaker Project` notebook in /Project

## Expected behavior

In general, any unpaginated approach is undesirable and the default behavior of the extension should provide sensible defaults that are performant. For e.g, in the `/git/all_history` API, the output from `git log` is intentionally restricted to 10 by default to avoid such scenarios (See https://github.com/jupyterlab/jupyterlab-git/blob/master/jupyterlab_git/git.py#L317-L325).  

Since there is no native pagination in the `git status` command and the adverse effects of this issue,  the proposed approach is to just use `-u='normal'` or omit the option altogether. (https://git-scm.com/docs/git-status#Documentation/git-status.txt---untracked-filesltmodegt). This option doesn't recursive list every untracked file in each sub-directory and still returns a reasonable default . This is the same UX as just doing `git status` in a terminal. Power users can fall back to the terminal to display each untracked file using additional flags in the API.
 
## Context

- Python package version: 0.10.1

- Extension version: 0.10.1

- Git version: 2.13

- Operating System and its version: Amazon Linux

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

### PR DESCRIPTION
**Pull request by fcollonval**
Use a virtual component to display files list.

Fixes #667 
Closes #703 
Closes #704

TODO
- [x] Set nice height strategy
- [x] Set windowing on history file list
- [x] Set windowing on branch list

### CODE REVIEW

**Comment by fcollonval** [comment]
This is an early prototype - styling issues need to be addressed (i.e. height handling). But at least it shows that windowing the files list will fix the performance issue.

**Comment by fcollonval** [comment]
@ianhi I'll go ahead and merge this one as I need it for other improvements. But if you could check you don't see any glitches on the master after that, I'll appreciate.

**Comment by ianhi** [comment]
:+1:  will do

**Comment by ianhi** [comment]
This fixes the total freezing of the UI and I don't think it introduced any bugs -  so hooray!

We should maybe still consider compressing the result of status? When I create 10000 files the status request starts to get large and while it's still pretty quick at `65` ms if it gets much longer I suspect it will start to feel laggy:
image

At least one person reported that the payload was very large for them: https://github.com/jupyterlab/jupyterlab-git/issues/667#issuecomment-642940456

**Comment by ZhangHan** [comment]
@fcollonval Great this gets fixed in 0.2.X! Is there any concern back porting this fix to 0.10.x and include in a new release?

**Comment by fcollonval** [comment]
> @fcollonval Great this gets fixed in 0.2.X! Is there any concern back porting this fix to 0.10.x and include in a new release? 

We don't have bandwidth to support older versions. But if you are willing to help. You could trigger a backport with the following comment:

> @meeseeksdev backport to 0.10.x

If you succeed to make it works. I can make a release.

Small question why not on 0.11.x as that is the latest version for JupyterLab 1?

**Pull request merged**
