### PR TITLE
Rename extension API method, provide interface

### LINKED ISSUE #192: Add extension point: Diff viewers
I'm working on [nbdime](https://github.com/jupyter/nbdime), which also has a jupyterlab extension. Currently the labextension only supports diffing the current version of the file on disk vs git HEAD. While this is useful, if it was integrated with jupyterlab-git, it could support diffing any git refs of notebooks. This would help push use of git/VCS for notebooks, which is a Good Thing!

There are many ways to achieve such an integration, but I think my favorite is like this:
- the jupyterlab-git extension provides an interface, with a function for registering a diff provider, e.g. with a signature like this: `registerDiffProvider(fileExtensions: string[], provider: (path: string, revA: string, revB: string) => void): void` (or possibly, define an interface for the diff provider). It could then also have a helper function to get the notebook content for a specific revision (`getFile(path: string, revision: string): INotebook`).
- jupyterlab-git might then want to supply a default diff viewer (line-based string differ) based on a standard JS diff lib.

The advantages to this approach:
- no dependencies for jupyterlab-git.
- providers like nbdime can have an optional requires of the provided interface!
- easy for third-party developers to add support for more file formats (e.g. Word or PDF files).
- simple API.

### PR DESCRIPTION
**Pull request by vidartf**
- Rename `register_diff_provider` --> `registerDiffProvider`.
- Ensure `IGitExtension` is listed in `provides` of plugin.
- Re-order declarations to enable previous point (and help reading of code).

TODO: Still untested. I'll try to develop against this locally with nbdime and see if I can get this to work. If and when, I'll ping this PR again!

Fixes #192.

### CODE REVIEW

**Comment by vidartf** [comment]
I've been working on this locally with nbdime, and it seems like it works now except one issue: If the repository root and the file browser root does not match, I struggle to find the correct file. So the diff callback should get the path to the file relative to the notebook server root! I'd love it if someone more familiar with the jupyterlab-git codebase could look at that!

**Comment by ellisonbg** [comment]
Hi @vidartf thanks for submitting this! We are getting going on this extension again and I know there is interest in having this work. @jaipreet-s could you have a look at this and figure out how this will figure in the roadmap?

**Comment by vidartf** [comment]
Thanks for the ping. I did a rebase to fix the merge conflicts.

**Comment by vidartf** [comment]
Seems it got some fresh conflicts again, so please review as-is, and I'll resolve those once it has been green-lit.

**Comment by tgeorgeux** [comment]
@jaipreet-s I'm sitting here with @vidartf who wrote and maintains NBDime. He wanted to check in on the status of NBDime integration, do we have the diff view in NBDime working at this point?

**Comment by saulshanabrook** [comment]
@jaipreet-s Vidar was asking me if he should rebase this and get it up to date, so that we can can get it in. 

Do you have any opinion about this PR and if it is worth cleaning up to get in?

**Comment by vidartf** [comment]
Just to add some context here:
- The interface is intended to allow other extensions to register themselves as diff viewers for specific filetypes (the `registerDiffProvider` on the interface `IGitExtension`). One of the principal consumers of this interface would be nbdime's lab extension, which would provide better diffs of notebooks.
- This was previously sprinted on (`register_diff_provider`), but never completed to a working state. This PR is meant to address that.

**Comment by vidartf** [comment]
For further context, see the issue that this is supposed to fix, #192.

**Comment by jaipreet-s** [comment]
@vidartf sounds good! Let's merge this in and iterate on it.

**Comment by vidartf** [comment]
@jaipreet-s Just force pushed after rebase.

**Pull request merged**
